/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app;

import java.awt.Image;

import java.io.IOException;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.io.PrintWriter;
import java.net.Socket;
import java.util.ArrayList;

/**
 *
 * @author INSECT
 */
public class HomaPageChatApp extends javax.swing.JFrame {

    public static HomaPageChatApp app;
    public static String clientToNames, localhostAddress = "localhost";
    public static ArrayList<String> clients = new ArrayList();
    public static int portNumber = 1111;
    public static Boolean connected = false;

    public static Socket SSocket;
    public static PrintWriter printWriter;
    public static BufferedReader bufferReader;

    public void ListenThread() {
        Thread PClient = new Thread(new PClient());
        PClient.start();
    }

    public void removeToClients(String data) {
        jTextArea2.append(data + "Çıkış yaptı... ");
    }

    public void addToClients(String data) {
        clients.add(data);
    }

    public void writeToClients() {
        String[] temperoryList = new String[(clients.size())];
        clients.toArray(temperoryList);
        for (String token : temperoryList) {
            //clients.append(token + "\n");   
        }
    }

    public void sendDisconnect() {
        String bye = (clientToNames + ": :Artık Bağlı Değil...");
        {
            try {
                printWriter.println(bye);
                printWriter.flush();
            } catch (Exception ex) {
                jTextArea2.append("... \n");
            }
        }
    }

    public void Disconnect() {
        try {
            SSocket.close();
        } catch (Exception e) {
            jTextArea2.append("Client Fail Oldu \n");
        }
        connected = false;
        jTextArea2.setEditable(true);
    }

    public HomaPageChatApp() {
        initComponents();
    }

    public class PClient implements Runnable {

        @Override
        public void run() {

            String stream;
            String[] display;
            String connect = "Connect";
            String disconnect = "Disconnect";
            String chat = "Chat";
            String room = "Room";
            String done = "Done";
            try {
                while ((stream = bufferReader.readLine()) != null) {
                    display = stream.split(":");
                    if (display[2].equals(chat)) {
                        jTextArea2.append(display[0] + ":" + display[1] + "\n");
                        jTextArea2.setCaretPosition(jTextArea2.getDocument().getLength());
                    } else if (display[2].equals(connect)) {
                        jTextArea2.removeAll();
                        addToClients(display[0]);
                    } else if (display[2].equals(disconnect)) {
                        removeToClients(display[0]);
                    }
                    writeToClients();
                    clients.clear();
                }

            } catch (Exception e) {
            }

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        txt_name = new javax.swing.JTextField();
        btn_connect = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        btn_connect1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btn_connect2 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nameActionPerformed(evt);
            }
        });
        getContentPane().add(txt_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 100, 30));

        btn_connect.setBackground(new java.awt.Color(255, 0, 0));
        btn_connect.setFont(new java.awt.Font("Bell Gothic Std Black", 1, 12)); // NOI18N
        btn_connect.setText("Çıkıs");
        btn_connect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_connectActionPerformed(evt);
            }
        });
        getContentPane().add(btn_connect, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, 70, 30));

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane3.setViewportView(jTextArea2);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 210, 150));

        jLabel4.setFont(new java.awt.Font("Bell Gothic Std Black", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("Sohbet Penceresi");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, -1, -1));

        btn_connect1.setBackground(new java.awt.Color(255, 0, 0));
        btn_connect1.setFont(new java.awt.Font("Bell Gothic Std Black", 1, 12)); // NOI18N
        btn_connect1.setText("Kayıt Ol");
        btn_connect1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_connect1ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_connect1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 160, 30));

        jLabel6.setFont(new java.awt.Font("Bell Gothic Std Black", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 51, 51));
        jLabel6.setText("Nick");
        jLabel6.setToolTipText("");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, 20));

        btn_connect2.setBackground(new java.awt.Color(255, 0, 0));
        btn_connect2.setFont(new java.awt.Font("Bell Gothic Std Black", 1, 12)); // NOI18N
        btn_connect2.setText("Mesaj gönder");
        btn_connect2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_connect2ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_connect2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 210, 30));

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 210, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_connectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_connectActionPerformed
        sendDisconnect();
        Disconnect();
//

    }//GEN-LAST:event_btn_connectActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing

    }//GEN-LAST:event_formWindowClosing

    private void txt_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nameActionPerformed

    private void btn_connect1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_connect1ActionPerformed
        if (connected == false) {
            clientToNames = txt_name.getText();
            txt_name.setEditable(false);

            try {
                SSocket = new Socket(localhostAddress, portNumber);
                InputStreamReader streamreader = new InputStreamReader(SSocket.getInputStream());
                bufferReader = new BufferedReader(streamreader);
                printWriter = new PrintWriter(SSocket.getOutputStream());
                printWriter.println(clientToNames + " :Client bağlı : client ");
                printWriter.flush();
                connected = true;
                txt_name.setEnabled(false);
            } catch (Exception e) {
                txt_name.setEditable(true);
            }
            ListenThread();

        } else if (connected == true) {
            jTextArea2.append("Sunucuya zaten bağlısınız. \n");
        }

    }//GEN-LAST:event_btn_connect1ActionPerformed

    private void btn_connect2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_connect2ActionPerformed
        String nothing_Found = "";
        if ((jTextField2.getText()).equals(nothing_Found)) {
            jTextField2.setText("");
            jTextField2.requestFocus();
        } else {
            try {
                printWriter.println(clientToNames + ":" + jTextField2.getText() + ":" + "Chat");
                printWriter.flush();
            } catch (Exception e) {
                jTextArea2.append("Mesaj Gönderilemedi! \n");
            }
            jTextField2.setText("");
            jTextField2.requestFocus();
        }
        jTextField2.setText("");
        jTextField2.requestFocus();

    }//GEN-LAST:event_btn_connect2ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomaPageChatApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomaPageChatApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomaPageChatApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomaPageChatApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomaPageChatApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_connect;
    public javax.swing.JButton btn_connect1;
    public javax.swing.JButton btn_connect2;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane3;
    public javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField2;
    public javax.swing.JTextField txt_name;
    // End of variables declaration//GEN-END:variables
}
