/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chatappserver;

import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.io.PrintWriter;
import java.net.ServerSocket;
import java.net.Socket;
import java.util.ArrayList;
import java.util.Iterator;

/**
 *
 * @author MERT
 */
public class ChatAppServer extends javax.swing.JFrame {

    /**
     * Creates new form FrmServer
     */
    ArrayList clientOutputStreams;
    ArrayList<String> username;

    public class Client implements Runnable {

        BufferedReader bufferReader;
        Socket SSocket;
        PrintWriter client;

        public Client(Socket clientSocket, PrintWriter user) {
            client = user;
            try {
                SSocket = clientSocket;
                InputStreamReader isReader = new InputStreamReader(SSocket.getInputStream());
                bufferReader = new BufferedReader(isReader);
            } catch (Exception e) {
                jTextArea1.append("Unexpected error. . . \n");
            }
        }

        /**
         * Creates new form Frame_server
         */
        @Override
        public void run() {
            String message;
            String chat = "Chat";
            String disconnect = "Disconnect";
            String connect = "Connect";
            String room = "Room";
            String[] dataset;

            try {
                while ((message = bufferReader.readLine()) != null) {
                    jTextArea1.append("Online:  " + message);
                    dataset = message.split(":");

                    for (String token : dataset) {
                        jTextArea1.append(token + "\n");
                    }
                    if (dataset[2].equals(connect)) {
                        callClients((dataset[0] + ":" + dataset[1] + ":" + chat));
                    } else if (dataset[2].equals(disconnect)) {
                        callClients((dataset[0] + ":Artık bağlı değil" + ":" + chat));
                        clientRemove(dataset[0]);
                    } else if (dataset[2].equals(chat)) {
                        callClients(message);
                    }
                    /*else {
                        jTextArea1.append("the conditions are not met. \n");
                    }*/
                }
            } catch (Exception e) {
                e.printStackTrace();
                clientOutputStreams.remove(client);
            }
        }
    }

    public ChatAppServer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_connect1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        btn_connect4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_connect1.setBackground(new java.awt.Color(255, 0, 0));
        btn_connect1.setFont(new java.awt.Font("Bell Gothic Std Black", 1, 12)); // NOI18N
        btn_connect1.setText("Start");
        btn_connect1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_connect1ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        btn_connect4.setBackground(new java.awt.Color(255, 0, 0));
        btn_connect4.setFont(new java.awt.Font("Bell Gothic Std Black", 1, 12)); // NOI18N
        btn_connect4.setText("Stop");
        btn_connect4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_connect4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_connect1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_connect4, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_connect1)
                    .addComponent(btn_connect4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                .addGap(63, 63, 63))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_connect1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_connect1ActionPerformed

        Thread starter = new Thread(new ServerStart());
        starter.start();

        jTextArea1.append("Server açıldı!! \n");
    }//GEN-LAST:event_btn_connect1ActionPerformed

    private void btn_connect4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_connect4ActionPerformed
        // TODO add your handling code here:
        try {
            Thread.sleep(6999);
        } catch (InterruptedException e) {
            Thread.currentThread().interrupt();
        }

        callClients("Server: Chat App Serveri Durduruldu....  \n");
        jTextArea1.append("Chat App Serveri Durduruldu....  \n");
        jTextArea1.setText("");

    }//GEN-LAST:event_btn_connect4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChatAppServer.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChatAppServer.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChatAppServer.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChatAppServer.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChatAppServer().setVisible(true);
            }
        });
    }

    public class ServerStart implements Runnable {

        @Override
        public void run() {
            clientOutputStreams = new ArrayList();
            username = new ArrayList();

            try {
                ServerSocket serverS = new ServerSocket(1111);

                while (true) {
                    Socket clientS = serverS.accept();
                    PrintWriter writer = new PrintWriter(clientS.getOutputStream());
                    clientOutputStreams.add(writer);

                    Thread listener = new Thread(new Client(clientS, writer));
                    listener.start();
                }
            } catch (Exception e) {

            }
        }
    }

    public void addToClients(String dataset) {
        String message, add = ": :Connect", done = "Server: :Done", name = dataset;
        jTextArea1.append("Before " + name + "added. \n");
        username.add(name);
        jTextArea1.append("After " + name + " added. \n");
        String[] temperoryList = new String[(username.size())];
        username.toArray(temperoryList);

        for (String token : temperoryList) {
            message = (token + add);
            callClients(message);
        }
        callClients(done);
    }

    public void clientRemove(String dataset) {
        String message, add = " : :Connect", done = "Server: :Done", name = dataset;
        username.remove(name);
        String[] temperoryList = new String[(username.size())];
        username.toArray(temperoryList);
        for (String token : temperoryList) {
            message = (token + add);
            callClients(message);
        }
        callClients(done);
    }

    public void callClients(String message) {
        Iterator it = clientOutputStreams.iterator();

        while (it.hasNext()) {
            try {
                PrintWriter writer = (PrintWriter) it.next();
                writer.println(message);
                jTextArea1.append("Client mesajı: " + message + "\n");
                writer.flush();
                jTextArea1.setCaretPosition(jTextArea1.getDocument().getLength());
            } catch (Exception e) {
                jTextArea1.append("Hata aldınız!! \n");
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_connect1;
    public javax.swing.JButton btn_connect4;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
